baseURL = 'https://kylernats.github.io/personal-blog/'
languageCode = 'en-us'
title = 'Kyler Nats | Cybersecurity Portfolio'
theme = "PaperMod"

[params]
    env = "production"
    description = "MS in MIS Student @ U of A | Cybersecurity & Cloud Security"
    author = "Kyler Nats"
    
    [params.profileMode]
        enabled = false # Disables centered mode to allow side-by-side layout

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # Allows PDF <object> embedding

# Navigation Menu
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 10
[[menu.main]]
    name = "Resume"
    url = "/resume/"
    weight = 20
[[menu.main]]
    name = "Security Projects"
    url = "/projects/"
    weight = 30
[[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 40
[[menu.main]]
    name = "Lessons Learned"
    url = "/lessons-learned/"
    weight = 50